### ISSUE TITLE
[BUG] DockDoor previews are unstable

### ISSUE THREAD

**Issue by illavoluntas** [ejbills/DockDoor#243] opened 2024-08-06 10:13 UTC
DockDoor randomly does not show the previews when the Dock is hovered.

## Steps to reproduce
- Try to hover the preview to show a large preview, then go away. Try again and randomly no Dock preview nor large preview will appear.
- Restarting the app will fix the problem.

## Environment
 - macOS version: macOS Sonoma 14.5
 - App version: 1.1.5
 
## Note
~~This might be a cause/consequence of #244 because it seems to happen only with Adobe products.~~

**Comment by gkrawiec** [comment] 2024-08-07 17:35
i might have this same problem, though I cannot link it to first hovering on a preview. It seems to just stop working randomly, but not crashing. Restarting the app fixes it.

**Comment by illavoluntas** [comment] 2024-08-07 18:41
Author of #230 might have more informations about it.

**Comment by nkapila6** [comment] 2024-08-13 06:17
I'm facing the same issue. Works fine on a restart and then it just stops randomly.

**Comment by mchewy** [comment] 2024-08-13 11:50
I have the same issue but is not random for me - happens when the machine wakes from sleep. A quick restart of the dockdoor app fixes it, but would be great if we could get the issue addressed.

**Comment by illavoluntas** [comment] 2024-08-13 12:03
So this bug seems to be general. It might be a bug in some new features brought by 1.1.5. 
Could @ejbills or @ShlomoCode or anyone else in the development team try to investigate about it?

**Comment by illavoluntas** [comment] 2024-08-13 12:05
> I have the same issue but is not random for me - happens when the machine wakes from sleep. A quick restart of the dockdoor app fixes it, but would be great if we could get the issue addressed.

You may have spotted the problem. Now I notice DockDoor doesn’t work anymore after sleep.

**Comment by ShlomoCode** [comment] 2024-08-13 14:35
@mchewy @illavoluntas For me it continues to work even after sleep ("Sleep" item from the apple menu). Can you detail how to reproduce the bug?

**Comment by ShlomoCode** [comment] 2024-08-13 15:06
@gkrawiec It sounds more like Log Out than Sleep
Make sure that "Launch at login" is enabled for you in the DockDoor settings
![CleanShot 2024-08-13 at 18 04 59@2x](https://github.com/user-attachments/assets/a7bf9ae9-fcd9-4395-b0c4-71246609be98)

**Comment by gkrawiec** [comment] 2024-08-13 15:08
it happens randomly  while in my account and for sure when I return from another profile after LOCK SCREEN. There is no logout and the app is still open.

**Comment by ShlomoCode** [comment] 2024-08-13 15:14
Ok, I've now created a test user profile on my macbook, locked the screen and logged in to the new account, locked again and logged in to the regular account, and DockDoor still works. I'm at a dead end.

**Comment by ShlomoCode** [comment] 2024-08-13 15:34
Can you check if the window switcher continues to work even when dock preview stops?
Maybe macOS disables the eventTap (https://github.com/ejbills/DockDoor/issues/230#issuecomment-2250307889)
However, if this is the problem, it should be solved in a PR I'm preparing that completely removes the need for event tap and uses listening to the Dock events.

**Comment by illavoluntas** [comment] 2024-08-13 16:39
For me, the switcher also works when the previews do not work.

**Comment by gkrawiec** [comment] 2024-08-13 16:53
Sorry had to leave. I dont use the switcher (i use altTab for that) so i wasnt able to test.
Interestingly, now that I returned to my computer, after an hour of the computer sleeping, dockdoor is wortking again.
I cannot find a pattern yet. Seems to just stop whenever it feels like it and start again just as randomly.

> Can you check if the window switcher continues to work even when dock preview stops? Maybe macOS disables the eventTap ([#230 (comment)](https://github.com/ejbills/DockDoor/issues/230#issuecomment-2250307889)) However, if this is the problem, it should be solved in a PR I'm preparing that completely removes the need for event tap and uses listening to the Dock events.

**Comment by ShlomoCode** [comment] 2024-08-13 17:08
> Seems to just stop whenever it feels like it and start again just as randomly.

Hmmm... does it sometimes stop working and then work again without any action from you?

**Comment by illavoluntas** [comment] 2024-08-13 17:54
> > Seems to just stop whenever it feels like it and start again just as randomly.
> 
> Hmmm... does it sometimes stop working and then work again without any action from you?

In my experience I always have to restart the application, even after a few days. Within these days I use my Mac but I don’t restart DockDoor.

**Comment by hasansultan92** [comment] 2024-08-13 18:57
@gkrawiec @illavoluntas are you able to consistently replicate this issue? If so the next time this happens, can you open activity monitor, search for DockDoor, and send a screenshot of the CPU usage tab? We can check if its crashed or if its still alive using that because activity monitor will be able to tell if its not responsive.

**Comment by ShlomoCode** [comment] 2024-08-13 19:07
@hasansultan92 If the window switcher continues to work (as @illavoluntas wrote) it means that DockDoor continues to work, and the problem is probably in the event tap

**Comment by hasansultan92** [comment] 2024-08-13 19:46
@ShlomoCode agreed but there seemed to have been a possibility that perhaps the app might have crashed and hence the restart was required as written above by @gkrawiec so I want to verify if that is the case or not

**Comment by illavoluntas** [comment] 2024-08-13 19:52
> @gkrawiec @illavoluntas are you able to consistently replicate this issue? If so the next time this happens, can you open activity monitor, search for DockDoor, and send a screenshot of the CPU usage tab? We can check if its crashed or if its still alive using that because activity monitor will be able to tell if its not responsive.

Sure, I will look at it next time it happens.

**Comment by illavoluntas** [comment] 2024-08-13 20:43
> @gkrawiec @illavoluntas are you able to consistently replicate this issue? If so the next time this happens, can you open activity monitor, search for DockDoor, and send a screenshot of the CPU usage tab? We can check if its crashed or if its still alive using that because activity monitor will be able to tell if its not responsive.

DockDoor Dock previews just crashed **after watching a video with full screen**. Not sure if the context helps but it might. 
Here are screenshots of CPU and RAM activity. Cmd+Tab switcher still works fine.

![Capture d’écran 2024-08-13 à 22 39 11](https://github.com/user-attachments/assets/897d011d-8f0f-44bc-8986-036eb510ec71)
![Capture d’écran 2024-08-13 à 22 39 29](https://github.com/user-attachments/assets/918f5f85-fb2a-45b2-bc47-a2a7fb64168c)

**Comment by illavoluntas** [comment] 2024-08-13 20:47
Seems DockDoor is still responsive.
Tried monitoring CPU usage while DockDoor was normally functioning and it gets up to 20% CPU when moving the mouse fast. #190 
When mouse is idle then CPU usage is about the same as on the screenshot -- when it was not functioning properly. 0.2% CPU.

**Comment by gkrawiec** [comment] 2024-08-13 20:56
stopped working. I was just in a full screen google meet.
<img width="934" alt="90729" src="https://github.com/user-attachments/assets/ed6b9227-378e-4e4b-ad42-b5370b408d9d">

**Comment by ShlomoCode** [comment] 2024-08-13 20:56
> When mouse is idle then CPU usage is about the same as on the screenshot -- when it was not functioning properly. 0.2% CPU.

This proves the guess that the problem is disabling of the event tap

**Comment by ejbills** [comment] 2024-08-13 20:59
> This proves the guess that the problem is disabling of the event tap

Do your changes solve this issue inherently in the draft PR?

**Comment by illavoluntas** [comment] 2024-08-13 20:59
> stopped working. I was just in a full screen google meet. <img alt="90729" width="934" src="https://private-user-images.githubusercontent.com/645451/357569740-ed6b9227-378e-4e4b-ad42-b5370b408d9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1ODMwNTYsIm5iZiI6MTcyMzU4Mjc1NiwicGF0aCI6Ii82NDU0NTEvMzU3NTY5NzQwLWVkNmI5MjI3LTM3OGUtNGU0Yi1hZDQyLWI1MzcwYjQwOGQ5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QyMDU5MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzZlNTg5MjE4ZThmMWJlMjJkMGRmNWFiZmY5OTI1MGM0ZWMzZmQzOTcxODRmMDYwMmFhODA2MTg5YThmYTNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jBe5ceZ-AoC_KU2UHQRRfNHMPlNW-lbxYQzyoS_Fotk">

Could it be the full screen problem?

**Comment by ShlomoCode** [comment] 2024-08-13 21:02
> > This proves the guess that the problem is disabling of the event tap
> 
> Do your changes solve this issue inherently in the draft PR?

I think Yes, because I don't use a mouse event tap at all, I listen to the `kAXSelectedChildrenChangedNotification` event of the Dock app ax element

**Comment by ejbills** [comment] 2024-08-13 21:04
> I think Yes, because I don't use a mouse event tap at all, I listen to the `kAXSelectedChildrenChangedNotification` event of the Dock app ax element

Is it possible we cherrypick those changes onto the main branch so we can get it merged?

**Comment by ejbills** [comment] 2024-08-13 21:04
> Could the full screen mode be the problem?

I believe it's unrelated

**Comment by ShlomoCode** [comment] 2024-08-13 21:12
> > I think Yes, because I don't use a mouse event tap at all, I listen to the `kAXSelectedChildrenChangedNotification` event of the Dock app ax element
> 
> Is it possible we cherrypick those changes onto the main branch so we can get it merged?

Yes of course, I started working on it, I made a quick port of this part from #214, it works but not ready enough yet
Would you like to work on it together?

**Comment by ejbills** [comment] 2024-08-13 22:57
> > > I think Yes, because I don't use a mouse event tap at all, I listen to the `kAXSelectedChildrenChangedNotification` event of the Dock app ax element
> > 
> > 
> > Is it possible we cherrypick those changes onto the main branch so we can get it merged?
> 
> Yes of course, I started working on it, I made a quick port of this part from #214, it works but not ready enough yet Would you like to work on it together?

Yes, please open another draft or send me the info of how you want me to help out.

**Comment by ShlomoCode** [comment] 2024-08-14 00:57
@ejbills See PR https://github.com/ejbills/DockDoor/pull/254. The Dock functionality works, the window changer is still problematic.
Main points remaining:
1. https://github.com/ejbills/DockDoor/pull/254/files#diff-017b6b046f3844ad59afc9f7acd992ad75e9b77ec27f24b4186d13130fc73f20R85
2. The windows switcher is very slow to open
3. Maybe we should get the windows using kAXWindowsAttribute

Also, the code needs polishing, and better documentation of the changes in PR.

**Comment by mchewy** [comment] 2024-08-14 13:54
Not sure if it helps but previews just stopped working for me, seemingling randomly. I was viewing some viedos through Chrome, not fullscreen
![2024-08-14_09-50-03](https://github.com/user-attachments/assets/3f2576b3-8c15-40fe-a871-7365a70ec3e3)

**Comment by illavoluntas** [comment] 2024-08-14 14:00
Well, for now we haven’t seen any pattern on the failures. Just DockDoor Dock previews randomly failing.

**Comment by illavoluntas** [comment] 2024-08-14 14:01
Seems DockDoor does not survive a day. In my experience it crashes about 2 or 3 hours after restarting the app

**Comment by marcelharinck** [comment] 2024-08-23 08:38
I'm having the same issue since App version: 1.1.5 i believe.

**Comment by MattSuda** [comment] 2024-08-29 02:32
I've been having this same issue after a recent DockDoor update

**Comment by illavoluntas** [comment] 2024-08-29 05:47
OK, thank you all for reporting this malfunction. **Version 1.1.5 is faulty here. Something was added and caused unexplained crashes. I think this will be addressed in the next version.**

**Comment by illavoluntas** [comment] 2024-08-31 15:49
It looks like version 1.1.6 addressed the issue. I'm keeping it open for a few days to make sure the patch is real.

**Comment by ejbills** [comment] 2024-08-31 15:51
1.1.6 does not address this issue, this issue will be fixed in this PR: https://github.com/ejbills/DockDoor/pull/254

It is almost done.

**Closed** 2024-09-04 00:07 UTC
Labels: bug
