### ISSUE TITLE
Window switch keybinding change?

### ISSUE THREAD

**Issue by pencilcheck** [ejbills/DockDoor#81] opened 2024-07-06 18:42 UTC
The ctrl tab is overriding the tab switching in safari and other browsers, would be nice if we can change the key binding to something else.

**Comment by ejbills** [comment] 2024-07-06 18:44
This feature is currently almost done! @hasansultan92 is working on it. Closing this as it is a duplicate of https://github.com/ejbills/DockDoor/issues/11

**Closed by ejbills** 2024-07-06 18:44 UTC
