### ISSUE TITLE
Please add an option to not change window order when switching windows

### ISSUE THREAD

**Issue by YousufSSyed** [ejbills/DockDoor#198] opened 2024-07-16 17:41 UTC

**Comment by ShlomoCode** [comment] 2024-07-16 22:48
duplicate of https://github.com/ejbills/DockDoor/issues/196

**Closed** 2024-07-16 23:33 UTC

**Comment by ShlomoCode** [comment] 2024-07-17 17:00
Sorry but I could not understand what problem you are complaining about. Could you perhaps elaborate more? Maybe upload a screen recording?

**Comment by hasansultan92** [comment] 2024-07-22 11:31
@YousufSSyed I am coming across this issue right now. If I understand correctly, lets assume you have 4 Firefox windows, window a,x,y,z respectively. You want the dock to present the window in order of a,x,y,z all the time and never whichever window was most recently used? Lets say you use window y and then z, the order for the windows to show up in the dock preview would be y,z,a,x but you want to stick with a,x,y,z?

**Comment by YousufSSyed** [comment] 2024-07-22 19:22
@hasansultan92 @ShlomoCode Yes that's exactly what I meant.

**Comment by hasansultan92** [comment] 2024-07-23 13:32
Ah ok. The current PR I am working towards is actually going to change the order to the recently used application window. What is your recommendation based on this PR @ejbills? Do we add a settings pane to change the order of windows presented on the dock?
