### ISSUE TITLE
[BUG] Window delay popup is not honored once the previews are visible.

### ISSUE THREAD

**Issue by skynet01** [ejbills/DockDoor#231] opened 2024-07-24 21:58 UTC
## Describe the bug
The core issue is that when you have more than one window open you may have to slide your mouse diagonally to get to the window which means your mouse will pass an icon to the right or left. This will result in a popup for that window, and close the preview you were actually trying to select.  

A popup delay should fix this issue however the delay is not honored once there is a popup already being shown. 

## Steps to reproduce
Try to select a preview window but instead of dragging mouse straight up from the icon drag it diagonally (thus passing an icon next to the one on the left or right) to the preview that you need.  See video below. 

## Expected behavior
I am allowed to click on the window that's already created .. that I want to click :) 

## Actual behavior
Preview popup disappears and I see the wrong popup

## Screenshots
[Video Preview ](https://secure.fabriceleven.com/v/NxdAQN)

## Environment
 - macOS version: macOS 15.0 Sequoia
 - App version: 1.1.4

**Comment by illavoluntas** [comment] 2024-07-25 06:34
Have you tried changing the window buffer?

**Comment by skynet01** [comment] 2024-07-25 22:50
No the buffer doesn't change anything. The issue is there even if hiding is disabled. Obviously, if you go straight up it doesn't happen. 
The issue is that I have to consciously think about it which defeats the whole purpose of quickly jumping to my needed window. It's just frustrating to the point where I waste more time doing it "right"  (have it mess up, get frustrating, then going back the right away and carefully moving it up..) at this point I wasted 5 seconds and I just want to turn it off all together.

**Comment by illavoluntas** [comment] 2024-07-26 06:05
Oh, I understand your thoughts. It is indeed time-consuming…

**Comment by ShlomoCode** [comment] 2024-07-30 01:53
duplicate of https://github.com/ejbills/DockDoor/issues/54

**Comment by ejbills** [comment] 2024-08-07 00:18
Closing as duplicate - I will be looking into this this week.

**Closed by ejbills** 2024-08-07 00:18 UTC
Labels: bug
