### ISSUE TITLE
Dock peek isn't working at all if the app is in a different space, the app is opened, and all settings turned on, and permission given, still nothing...

### ISSUE THREAD

**Issue by pencilcheck** [ejbills/DockDoor#80] opened 2024-07-06 18:40 UTC
I'm on Sonoma 14.4.1

**Comment by ejbills** [comment] 2024-07-06 18:42
Duplicate of https://github.com/ejbills/DockDoor/issues/9

**Closed by ejbills** 2024-07-06 18:42 UTC
