### ISSUE TITLE
Bug: Calculator and Photos aren’t recognized

### ISSUE THREAD

**Issue by illavoluntas** [ejbills/DockDoor#163] opened 2024-07-11 12:03 UTC
https://github.com/ejbills/DockDoor/assets/174935274/e3a323d2-8923-4451-bb1a-b32561ae9199

Demonstration between Font Book and Calculator shows Calculator is not recognized by app.

**Comment by ejbills** [comment] 2024-07-11 13:35
Hoping this isnt due to localization... @ShlomoCode have you been having any other issues with localized bundle identifiers beyond our patch go fix that?

I have some questions: 
And does calculator just never work? Try relaunching it? What if you make the calculator window bigger? Does it show up in the window switcher?

**Comment by illavoluntas** [comment] 2024-07-11 13:44
@ejbills Tried several times, Calculator isn’t detected. Trying to make the calculator window bigger implies to activate the scientific mode and it still does not work.
When checking with the window switcher, Calculator preview does not show up. 

Changing the locale back to English does not fix it.

**Comment by illavoluntas** [comment] 2024-07-11 13:55
@ejbills Are you able to reproduce the issue?

**Comment by ShlomoCode** [comment] 2024-07-11 15:11
This happens for me even though the language of the system and the calculator app is English. So it seems to be unrelated to localization

**Comment by ejbills** [comment] 2024-07-11 15:14
Calculator works for me, not able to reproduce... could one of you dump the window info logs?

**Comment by ShlomoCode** [comment] 2024-07-11 15:59
I think I found it, but I don't have time right now to work on a fix
![CleanShot 2024-07-11 at 18 57 40@2x](https://github.com/ejbills/DockDoor/assets/78599753/88d1b626-118a-41ac-864e-949f4fea35d7)

Some more screenshots
![CleanShot 2024-07-11 at 18 50 34@2x](https://github.com/ejbills/DockDoor/assets/78599753/b455d8ab-a405-49d2-a357-fa8441e0efec)
![CleanShot 2024-07-11 at 18 52 23@2x](https://github.com/ejbills/DockDoor/assets/78599753/924eabed-2184-4907-9adb-70dce23a88f3)

**Comment by ejbills** [comment] 2024-07-11 16:00
Hmm.. that filtering is needed for other applications. Perhaps we can maintain a list of bundle IDs which are allowed to have empty window names (like calculator)?

**Comment by ShlomoCode** [comment] 2024-07-11 16:02
What applications is it for?

**Comment by ejbills** [comment] 2024-07-11 16:04
https://github.com/ejbills/DockDoor/issues/36

It was a fix for this issue, I didn't track the associated commit properly - but I just added the empty title check.

**Comment by ShlomoCode** [comment] 2024-07-11 16:08
Maybe we could instead check by minimum window size to show up in DockDoor?

**Comment by ShlomoCode** [comment] 2024-07-11 16:18
I see that alt tab uses a bunch of private CG APIs to get more information

**Comment by MattSuda** [comment] 2024-07-12 07:59
I have the same problem with the built in Photos app from Apple. 

When the Photos app is open and you hover over the app icon in the dock, there is no preview pop up.

**Comment by ejbills** [comment] 2024-07-12 15:07
Since the fix for https://github.com/ejbills/DockDoor/issues/36 seems to be causing cascading effects with other apps, it might be worth reverting the changes and reopening that initial issue.

**Comment by ShlomoCode** [comment] 2024-07-12 16:10
I agree

**Comment by ejbills** [comment] 2024-07-16 23:17
This will be addressed in the next release.

**Closed by ejbills** 2024-07-16 23:17 UTC
