### ISSUE TITLE
[FR]Hide app name when mouse hove the app icon

### ISSUE THREAD

**Issue by ErickWei** [ejbills/DockDoor#381] opened 2024-11-27 01:32 UTC
## Problem or Need
The cause is that i don't want show the app Name and preview at the same time[App Name-This is really ugly and unnecessary]
<img width="415" alt="image" src="https://github.com/user-attachments/assets/ef04b207-daf5-4e9a-964b-7106888107a6">

So i found a way to 'hide' app name like below:
-------------------------------------------------------
1. Go to /Users/Your Name/Library/Preferences/
2. Open com.apple.dock.plist (It should open in Property List Editor)
3. In the Editor disclose Root >> persistent-apps >> 0 >> Tile Data
4. set file-label to empty
-------------------------------------------------------

But after i 'hide' the app name,the preview for this app is not show too.

## Proposed Solution
I have 2 solution for this:
1:Add a feature to hide app's name while mouse hove the app icon on dock.Really looking forward to using this solution.
2:May be DockDoor using com.apple.dock.plist to show preview too.Adjust some policies so that apps with empty file-labels can preview。

## macOS Version
macOS 14.7 Sonoma

## App Version
1.3

- ✅ I have reviewed the open issues to ensure this is not a duplicate feature request

**Comment by illavoluntas** [comment] 2024-11-27 15:06
Duplicate of #140

**Comment by ejbills** [comment] 2024-11-27 15:44
@ErickWei discussion is moving to above issue. I will look into the dock plist attribute you mentioned, hopefully it can work with DockDoor. Thanks for the report!

**Closed by ejbills** 2024-11-27 15:44 UTC
Labels: enhancement
