### ISSUE TITLE
Preview for Fullscreen

### ISSUE THREAD

**Issue by mehapps** [ejbills/DockDoor#139] opened 2024-07-10 20:45 UTC
Hey! Would love to be able to get previews for fullscreen windows on a diff monitor

**Comment by ejbills** [comment] 2024-07-11 23:18
Closing, duplicate of https://github.com/ejbills/DockDoor/issues/32
(i just finished this feature :))

**Closed by ejbills** 2024-07-11 23:18 UTC

**Comment by ejbills** [comment] 2024-07-12 00:33
out now!
