### ISSUE TITLE
[FR] Make window selection more prominent

### ISSUE THREAD

**Issue by tmnrdhf** [ejbills/DockDoor#340] opened 2024-10-15 19:07 UTC
## Problem or Need
Currently the selected window in dock preview and window switcher is barely visible. There is just a very subtle colored layer (which also weirdly changes unless you adjust the settings) and the window slightly increases in size. (I don't even want to imagine how it is visually impaired people.)

## Proposed Solution
Could the selected window be made more visible? I think AltTab does it very well, see example [here](https://alt-tab-macos.netlify.app/public/demo/frontpage.jpg).

- [x] I have reviewed the open issues to ensure this is not a duplicate feature request

**Comment by illavoluntas** [comment] 2024-10-17 18:32
Looks like a duplicate of #260, reopened it now

**Comment by ejbills** [comment] 2024-11-25 18:08
Combining with https://github.com/ejbills/DockDoor/issues/340

Addressing this issue in 1.3.1

**Closed by ejbills** 2024-11-25 18:08 UTC
Labels: enhancement
