### ISSUE TITLE
[FR] Offer grid option in Window Switcher

### ISSUE THREAD

**Issue by stevehoek** [ejbills/DockDoor#319] opened 2024-09-13 20:51 UTC
## Problem or Need
Depending on the number of open app windows and the preview window size settings, the Window Switcher often can't show all window previews with its current design of a single row of window preview images.

## Proposed Solution
Offer a grid option (more like Windows or AltTab on macOS)

## Alternative Solutions
Not use DockDoor Window Switcher

## Additional context
trying to switch from AltTab to DockDoor for Window Switcher, but this is preventing me

## Potential Impact
More user choice

## macOS Version
latest public macOS

## App Version
latest

- [x ] I have reviewed the open issues to ensure this is not a duplicate feature request

**Comment by iamEvanYT** [comment] 2024-09-14 13:40
https://github.com/ejbills/DockDoor/pull/304 seems to be implementing this feature request.

**Comment by ejbills** [comment] 2024-09-14 14:04
Duplicate of https://github.com/ejbills/DockDoor/issues/84

**Closed by ejbills** 2024-09-14 14:04 UTC
Labels: enhancement
