### ISSUE TITLE
Add delay when removing mouse from icon

### ISSUE THREAD

**Issue by the-0verlord** [ejbills/DockDoor#217] opened 2024-07-18 03:42 UTC
When there are multiple window previews, it is natural to move the mouse diagonally to the desired window. However, I always end up mousing over a different icon and activating window previews for that app. I would like there to be a delay between when my mouse leaves the icon and when the next preview can pop up

**Comment by ejbills** [comment] 2024-07-18 14:36
Duplicate of https://github.com/ejbills/DockDoor/issues/212

**Closed by ejbills** 2024-07-18 14:36 UTC
