### ISSUE TITLE
[BUG]sometimes the preview window is very vague and margin is large

### ISSUE THREAD

**Issue by AstroCIEL** [ejbills/DockDoor#415] opened 2024-12-27 15:46 UTC
## Describe the bug
often the preview window is blurred and the margin is large.
<img width="488" alt="image" src="https://github.com/user-attachments/assets/be723d0c-3e26-4aaa-91d8-58f3060ea903" />
<img width="1005" alt="image" src="https://github.com/user-attachments/assets/f8cb201f-96fd-4e7a-bfe1-01306ee6382a" />
<img width="1185" alt="image" src="https://github.com/user-attachments/assets/d8781ad4-0e0f-4b48-8bc1-bb39b79d46f4" />

at the same time, some other apps are previewed normally.
<img width="1219" alt="image" src="https://github.com/user-attachments/assets/ff750c97-6ad7-417e-95ed-65ad5a3601eb" />

and I find it is not happening on specific apps; for a random app, its preview window sometimes acts normally while sometimes not.

## Steps to reproduce
- it happens all the time

## Expected behavior
all windows should be previewed clearly.

## Environment
 - macOS version: macOS 15.1.1 Sequoia
 - App version: 1.4

**Comment by ejbills** [comment] 2024-12-27 23:38
Duplicate of https://github.com/ejbills/DockDoor/issues/411

**Comment by ejbills** [comment] 2024-12-27 23:38
This will be addressed, looking into it now.

**Closed by ejbills** 2024-12-27 23:38 UTC
Labels: bug
