### ISSUE TITLE
[BUG] When focused window is on second monitor, dock previews are placed in the wrong location

### ISSUE THREAD

**Issue by bsiegel** [ejbills/DockDoor#277] opened 2024-08-29 21:27 UTC
## Describe the bug
When a window on my secondary monitor has focus, the dock preview seems to think it's in stage manager mode and shows previews vertically along the left edge of the primary monitor. See below.

## Steps to reproduce
- Have two monitors connected
- Open some windows, and have at least one on the secondary monitor (the monitor without the dock)
- Click within a window on the secondary monitor to focus it
- Now hover over an app icon in the dock on the primary monitor

## Expected behavior
The dock preview works as expected.

## Actual behavior
The dock preview seems to think it's in stage manager mode and shows previews vertically along the left edge of the primary monitor.

## Screenshots
![Screenshot 2024-08-29 at 2 26 57 PM](https://github.com/user-attachments/assets/789e60de-6e52-4181-9b10-353c4f3dee25)

## Environment
 - macOS version: 14.6.1
 - App version: 1.1.5

- [x] I have reviewed the open issues to ensure this is not a duplicate

**Comment by ejbills** [comment] 2024-08-29 23:26
Weird, I will look into this - thanks for the report.

**Comment by illavoluntas** [comment] 2024-08-30 07:40
Yes. I don’t think DockDoor *thinks it’s Stage Manager mode*, but chooses the wrong Dock. What is your configuration?
 Left: Secondary; Right: Primary?

**Comment by bsiegel** [comment] 2024-08-30 23:59
> Yes. I don’t think DockDoor _thinks it’s Stage Manager mode_, but chooses the wrong Dock. What is your configuration? Left: Secondary; Right: Primary?

Ah yep, that's correct. I have the primary monitor on the right and secondary on the left.

**Comment by illavoluntas** [comment] 2024-08-31 12:18
Thanks for confirming. Ejbills, I think DockDoor chooses the wrong Dock.

**Comment by ejbills** [comment] 2024-09-02 23:55
> Thanks for confirming, @bsiegel. Ejbills, I think DockDoor chooses the wrong Dock.

The mouse location was failing, leading to it defaulting to .zero (which is the bottom left corner of the main display). This will be fixed in the next release, I have attached the associated PR.

**Comment by bsiegel** [comment] 2024-09-04 17:29
@ejbills @illavoluntas This issue is not resolved in 1.2.0, can we re-open the ticket? Or would you prefer I create a new one?

**Comment by illavoluntas** [comment] 2024-09-04 17:46
> @ejbills @illavoluntas This issue is not resolved in 1.2.0, can we re-open the ticket? Or would you prefer I create a new one?

Did you try 1.2.1? I don’t know if the latter addresses this issue, but you might want to try.

**Comment by bsiegel** [comment] 2024-09-04 17:50
> > @ejbills @illavoluntas This issue is not resolved in 1.2.0, can we re-open the ticket? Or would you prefer I create a new one?
> 
> Did you try 1.2.1? I don’t know if the latter addresses this issue, but you might want to try.

Ahh, 1.2.1 was not showing up via autoupdate but I installed it from the GH releases - I can confirm the issue persists in 1.2.1 as well. Sorry for the bad news! And thank you both for your hard work and amazing responsiveness to issues here, this app solves a real problem in an incredible way and for how new it is I'm blown away with the level of quality and polish!

**Comment by illavoluntas** [comment] 2024-09-04 17:55
1.2.1 not showing correctly is expected for me because I noticed some files weren't changed correctly for the version bump. Some lines stayed at 1.2.0 and others went for 1.2.1. Well,I hope this error won't be repeated next time!

**Comment by illavoluntas** [comment] 2024-09-04 17:57
> @ejbills @illavoluntas This issue is not resolved in 1.2.0, can we re-open the ticket? Or would you prefer I create a new one?

I'll let ejbills decide, I'm not very familiar with GitHub issue conventions. He will be back soon I guess :)

**Comment by ejbills** [comment] 2024-09-04 20:00
@bsiegel I was able to reproduce this originally when I looked at the issue. After I pushed the fix, it works properly for me. I am unsure where to go next to try and replicate this issue. I tested on 2 and 3 monitors.

**Comment by ejbills** [comment] 2024-09-05 17:00
@bsiegel do you have dock hiding enabled? If not, can you toggle it on and see if the issue persists?

**Comment by ejbills** [comment] 2024-09-05 17:02
I would also like to know your monitor dimensions if possible. We have to use some math to get the dock position, it seems you have a high resolution monitor and a tiny dock, which may be revealing some issues with the math. If you enlarge the dock, does the issue go away?

**Comment by bsiegel** [comment] 2024-09-10 19:37
Sorry for the delay - following up with answers to your questions.

I don't have dock hiding enabled. When I turn it on, the issue is resolved - so it appears to only occur when dock hiding is disabled. After turning dock hiding back off, the issue reproduces again.

My dock tilesize is 36:
> $ defaults read com.apple.dock tilesize
> 36

I have 2x identical 2560x1440 (Lenovo L24q-20) monitors, set side-by-side. My main display is the monitor on the right.
![image](https://github.com/user-attachments/assets/47bc3818-8c03-430e-883a-945f9ae1c414)

**Comment by ejbills** [comment] 2024-09-12 05:23
I am migrating the dock calculations over to the CoreDock private API, which allows me to grab the size of the dock straight from the OS. Let's hope this finally fixes this issue.

**Closed** 2024-09-13 00:50 UTC
Labels: bug

**Comment by ejbills** [comment] 2024-09-13 01:17
Fixed @bsiegel
