### ISSUE TITLE
Dock peek: hover boundaries for dock icons are too easily triggered

### ISSUE THREAD

**Issue by 0n0mat0p03ia** [ejbills/DockDoor#15] opened 2024-06-24 20:01 UTC
The hover boundaries for dock icons are too easily triggered when attempting to select an item in the preview pop-up window. For example:

* Safari and Notes are adjacent in the dock. Safari to the left, Notes to the right
* Safari has two active windows in the preview pop-up, Safari-A (left) and Safari-B (right)

The user hovers over the Safari dock icon and Safari-A and Safari-B are displayed in the preview pop-up. The user moves the mouse cursor to select Safari-B. However, the cursor moves too close to the Notes dock icon and triggers its preview pop-up. 

In this scenario, if the Notes app was minimized or hidden, then when the Notes dock icon boundary is accidentally triggered, the Safari preview pop-up disappears, leaving the user confused. (It's because the app currently does not display previews for hidden or minimized apps, so nothing is displayed when the Notes boundary is triggered).

This has happened frequently enough to become an annoyance.

**Comment by ejbills** [comment] 2024-08-22 20:17
This will be in the next release. Also, it appears [issue 54](https://github.com/ejbills/DockDoor/issues/54) is a duplicate of this issue - but it has more discussion points so I will close this one now. Thanks @0n0mat0p03ia!

**Closed by ejbills** 2024-08-22 20:17 UTC
