### ISSUE TITLE
[BUG] Cursor tracking inaccurate: Dock Preview gets stuck and is displayed permanently

### ISSUE THREAD

**Issue by tmnrdhf** [ejbills/DockDoor#327] opened 2024-09-17 07:37 UTC
## Describe the bug

The easiest way to observe this:
- set the "Preview Window Open Delay" to 2 seconds
- move the cursor over an app icon
- and move it away _upwards_ quickly(!) above of the space where the previews would usually be displayed

After the delay, the preview will still appear which is already false because the mouse is not hovering over the app icon or an active preview anymore (but it also happens with no or very small delay settings). 

However, often times the preview does not even disappear anymore, sometimes you can even move your cursor sideways or downwards and nothing will happen. Only when you (significantly) move the cursor upwards the preview disappears. This behavior is especially annoying when you accidentally hover over the dock and then the preview is stuck on your screen.

## Expected behavior
The dock previews are only show while you hover directly over an app icon or an active preview

## Environment
 - macOS version: tested it on all supported macOS versions
 - App version: with the latest DockDoor version

## Additional context

- [x] I have reviewed the open issues to ensure this is not a duplicate

**Comment by ejbills** [comment] 2024-09-17 13:22
duplicate of https://github.com/ejbills/DockDoor/issues/17

**Closed by ejbills** 2024-09-17 13:22 UTC
Labels: bug
