### ISSUE TITLE
[BUG] some apps' windows were still shown after being closed

### ISSUE THREAD

**Issue by MinatoHikari** [ejbills/DockDoor#357] opened 2024-10-30 08:09 UTC
## Describe the bug
some apps' windows were still shown after being closed

## Steps to reproduce
install MacUpdater, open the app then close the window, then open a new one
install webstorm, then open a  project in welcome window

## Expected behavior
windows which were closed should not be previewed

## Actual behavior
welcome page of webstrom can be previewed
closed macupdater can be previewed

## Screenshots
![](https://s2.loli.net/2024/10/30/mR6ryzGQKMnSgp7.png)
![](https://s2.loli.net/2024/10/30/RNjzmPaX2g6nwh5.png)

## Environment
 - macOS version: 15.1
 - App version: 1.2.9

**Comment by illavoluntas** [comment] 2024-10-30 09:57
@ejbills Time to clean a bit these issues, duplicate of #330

**Closed** 2024-10-30 15:26 UTC
Labels: bug
