### ISSUE TITLE
[FR] [Optional] Open the window when hovering the preview

### ISSUE THREAD

**Issue by maranmaran** [ejbills/DockDoor#339] opened 2024-10-15 09:52 UTC
## Problem or Need
Optionally, opt-in open the actual window we are hovering in the preview. This is how WIN implementation does it by default if I'm not mistaken

## Proposed Solution
Show the hovered window (bring it to front, put it in focus) when hovering the preview, bring it back to wherever it was before (previous state) when hovering off the preview.

**Comment by ejbills** [comment] 2024-12-30 22:07
duplicate of https://github.com/ejbills/DockDoor/issues/248

**Closed** 2024-12-30 22:08 UTC
Labels: enhancement
