### ISSUE TITLE
[BUG] Preview windows randomly stop working until app restarted

### ISSUE THREAD

**Issue by mattjfra** [ejbills/DockDoor#289] opened 2024-09-04 08:34 UTC
## Describe the bug
Preview windows seem to randomly stop working until the app is restarted. I haven't yet managed to pinpoint any cause for this and the timeframe seems to be random (from 30 minutes to a few hours), so I appreciate it's about as wide open as you can get. The preview windows start working again once the app is restarted.

## Steps to reproduce

1. Start DockDoor
2. Wait until the preview window stops working on hover

## Expected behavior
For the preview window to appear on hover.

## Actual behavior
The preview window does not appear.

## Screenshots
<img width="762" alt="image" src="https://github.com/user-attachments/assets/7b9f819d-5846-484c-a4fe-01c54f5a026c">
<img width="762" alt="image" src="https://github.com/user-attachments/assets/036f88f6-953c-4702-a194-110a5327f7d1">

## Environment
 - macOS version: M3 Max, Sonoma 14.4
 - App version: 1.1.6

## Additional context
Not applicable.

- [x] I have reviewed the open issues to ensure this is not a duplicate

**Comment by illavoluntas** [comment] 2024-09-04 11:23
Duplicate of #243

**Closed** 2024-09-04 12:25 UTC
Labels: bug

**Comment by illavoluntas** [comment] 2024-09-04 13:17
@ejbills Hasn’t been this resolved? It should be closed as completed in my opinion.

**Comment by ejbills** [comment] 2024-09-04 15:53
> @ejbills Hasn’t been this resolved? It should be closed as completed in my opinion. 

Duplicates are closed as not planned.
