### ISSUE TITLE
Bug? Window title not permanently displayed

### ISSUE THREAD

**Issue by brunbjoern** [ejbills/DockDoor#185] opened 2024-07-14 15:47 UTC
(currently on 1.12, issue exists longer)

Altough "Show window title" is set to "always" it only shows the window title if I hover above it.
I want to see as quickly as possible to what window I would like to switch.

![Title Preview](https://github.com/user-attachments/assets/79c486d2-0601-4e5d-b06a-0ffdce9b4d5d)

Or did I understand the meaning of this setting wrong?

Many thanks for putting so much effort in this tool! I really appreciate it!

**Comment by chrisharper22** [comment] 2024-07-15 02:25
This is currently the intended behavior. But after seeing this, yes, it can be misleading. In the current context, "Always" actually means in both forms, not actually always. I will take a look at this.

**Comment by chrisharper22** [comment] 2024-07-15 03:18
This is adjusted in #187.

**Comment by ShlomoCode** [comment] 2024-07-15 18:00
The fix will be available in the next version. @ejbills It can be closed as fixed in https://github.com/ejbills/DockDoor/pull/188

**Closed** 2024-07-15 18:31 UTC
