### ISSUE TITLE
[FR] Multiple rows / grid for previews of large number of windows

### ISSUE THREAD

**Issue by simonnageleisen** [ejbills/DockDoor#361] opened 2024-11-05 22:44 UTC
## Problem or Need
If I have a large number of windows open for one app (eg. 20 browser windows (don't judge)) it only shows the preview for 8.5 of them on the size setting "Can you even see this?" and I have to scroll left/right to see more.

## Proposed Solution
If there are so many windows that they cannot all be shown in one row within the width of the screen, having them spill over into a second (...third etc.) row instead of keeping them in one row and forcing the user to scroll left/right to see the other previews.

## Alternative Solutions
Dynamically size the previews so all previews of the open windows of one app fit within the width of the screen (but yes, having 20 windows open probably would make the previews awfully small then)

## Additional context
Current DockDoor preview:
![CleanShot 2024-11-05 at 23 33 55@2x](https://github.com/user-attachments/assets/c9e8041d-7734-4ee2-9082-c342e44e46d9)

Example of desired preview (using DockMate):
![CleanShot 2024-11-05 at 23 35 44@2x](https://github.com/user-attachments/assets/5fd10464-8705-4c34-b4bb-174867a0f048)

Settings for this in DockMate:
![CleanShot 2024-11-05 at 23 41 15@2x](https://github.com/user-attachments/assets/2a871c9c-25eb-4eb4-820e-e07169e1b00e)

## Potential Impact
The user will be able to see all previews for all open windows of an app at once and does not need to scroll right to see older windows.

## macOS Version
15.1 Sequoia

## App Version
1.2.9

- [x] I have reviewed the open issues to ensure this is not a duplicate feature request

**Comment by simonnageleisen** [comment] 2024-11-05 22:56
Edit: Same thing for the _Alt + Tab_ Window switcher, that also seems to show all windows in one row.

**Comment by illavoluntas** [comment] 2024-11-06 11:51
@ejbills Duplicate of #84

**Closed** 2024-11-06 13:16 UTC
Labels: enhancement
