### ISSUE TITLE
[BUG] Safari download menu appears as its own window in DockDoor

### ISSUE THREAD

**Issue by itristenx** [ejbills/DockDoor#268] opened 2024-08-23 06:11 UTC
## Steps to reproduce
Open Safari
Download a file
Leave the downloaded files window open, and hover over the safari menu. The download menu is seen as a separate window instead on in-app menu. It also appears comically large. 

## Expected behavior
The download menu would not appear as a separate window. 

## Actual behavior
The download menu appears as its own window in DockDoor

## Screenshots
![image](https://github.com/user-attachments/assets/463b1c4b-421a-4649-aeba-6d62227dbdd7)

## Environment
 - macOS version: Mac OS 15.1
 - App version: 1.1.5

- [X] I have reviewed the open issues to ensure this is not a duplicate

**Comment by illavoluntas** [comment] 2024-08-23 08:54
Duplicate of #232

**Comment by ShlomoCode** [comment] 2024-08-23 13:12
@illavoluntas The issue you linked was closed as resolved on 1.1.15, this OP claims that this is not the case

**Comment by illavoluntas** [comment] 2024-08-23 17:08
Oh, sorry.

**Comment by ejbills** [comment] 2024-08-23 17:16
Realistically, it is a window that belongs to Safari, so it is a valid window. Does anyone have any ideas on how we can allow users to filter these windows? Maybe a customizable "minimum height/width" option which people can set to filter out small windows, like this downloads pane?

**Comment by illavoluntas** [comment] 2024-08-23 17:40
However, users may be confused if their terminal window (for example) is not displayed. Or other small windows.

**Comment by ejbills** [comment] 2024-08-23 18:35
Closing as this is the same issue as https://github.com/ejbills/DockDoor/issues/36

**Closed** 2024-08-24 00:05 UTC
Labels: bug
