### ISSUE TITLE
[FR] Integrate Window Previews Across All Mission Control Desktops

### ISSUE THREAD

**Issue by About7Deaths** [ejbills/DockDoor#359] opened 2024-11-01 22:42 UTC
## Problem or Need
What problem are you trying to solve? What need do you have that isn't currently met?

I use Mission Control to manage several desktops at the same time for work. It would be great if DockDoor had an option to preview windows across ALL desktops. So if I have 2 Chrome windows open on desktop 1, and 3 windows on desktop 2, I would like to see all 5 Chrome windows regardless of which desktop I currently have selected.

## Proposed Solution
How do you think this problem could be solved or this need could be met?

Monitor every window when a checkbox is selected in the setting panel, rather than just the windows within the current desktop.

## Alternative Solutions
Have you thought of any other ways to address this? If so, what are they?

I could try using DockDoor as a replacement for Mission Control and just use a single desktop, but that isn't ideal.

## Additional context

None

## Potential Impact
How would this feature benefit the project and its users?

It would allow for Mission Control to manage the grouping of various windows, but you could then use DockDoor to automatically switch to the right desktop. The current functionality of the dock when using multiple desktops is poor, and often when selecting the application it changes the desktop to the wrong window. Combining this with DockDoor would allow the user to select the exact window they are looking for in the preview selector.

## macOS Version
What version of macOS are you using? (e.g., macOS 15.0 Sequoia)

Sonoma 14.4

## App Version
What version of our app are you currently using? (e.g., 1.1.4)

v1.2.9

- [x] I have reviewed the open issues to ensure this is not a duplicate feature request

**Comment by About7Deaths** [comment] 2024-11-01 22:44
It looks like this sometimes already happens, but whenever I select a window that lives in a different desktop, nothing happens.

**Comment by hasansultan92** [comment] 2024-11-03 03:10
I believe we already have this going. You have to "discover" the open windows in different spaces when you launch the application by using the dock icon of the application or using the window switcher. After that DockDoor is able to keep track of all the windows and navigate to them.

**Comment by About7Deaths** [comment] 2024-11-03 15:13
> I believe we already have this going. You have to "discover" the open windows in different spaces when you launch the application by using the dock icon of the application or using the window switcher. After that DockDoor is able to keep track of all the windows and navigate to them.

Correct, I found this to be the case after experimenting for a few days. Would it be possible to allow switching desktops from just clicking a preview window? Currently you have to Command ⌘ + Click if the window exists in a different desktop.

**Comment by ejbills** [comment] 2024-11-25 18:00
Mine switches desktops without command clicking, I'm curious why yours is behaving like that. Can you try to disable the window switcher and see if you can switch desktops without command clicking just the hover previews?

**Comment by About7Deaths** [comment] 2024-11-27 23:14
> Mine switches desktops without command clicking, I'm curious why yours is behaving like that. Can you try to disable the window switcher and see if you can switch desktops without command clicking just the hover previews?

I disabled the window switcher and it behaves the same. This is using two incognito Chrome windows on two separate desktops. Clicking the preview once may take me to the new desktop, but selecting the other preview will not switch the desktop back to view of the second window, unless I command click the preview.

**Comment by ejbills** [comment] 2024-12-28 04:36
@About7Deaths I am closing this issue as the original issue was resolved based on the discussion. Your issue regarding the command + clicking, I am unable to reproduce. If you continue to experience this issue, please open a separate bug report for that. Based on my testing, the issue does not appear to be caused by DockDoor, and may be caused by another application on your system.

**Closed by ejbills** 2024-12-28 04:36 UTC
Labels: enhancement
