### ISSUE TITLE
[BUG] DD stops generating dock previews after a period of time

### ISSUE THREAD

**Issue by 0n0mat0p03ia** [ejbills/DockDoor#278] opened 2024-08-30 02:07 UTC
## Describe the bug
DD stops generating dock previews after a period of time. Not sure much time elapses before this occurs - at least a few days, perhaps more?

## Steps to reproduce
1. Launch DD

That's it. Eventually DD stops generating dock previews.

## Expected behavior
DD will generate dock previews indefinitely until the app is quit.

## Actual behavior
After a period of time elapses, DD stops generating dock previews when hovering over dock icons.

## Screenshots
N/A

## Environment
 - macOS version: 14.6.1
 - App version: 1.1.5

## Additional context
Issue is resolved after restarting.

- [X] I have reviewed the open issues to ensure this is not a duplicate

**Comment by ejbills** [comment] 2024-08-30 02:12
Please ensure you are checking for duplicates before opening. 

Closing as a duplicate of https://github.com/ejbills/DockDoor/issues/243

**Closed by ejbills** 2024-08-30 02:12 UTC
Labels: bug
